### ISSUE TITLE
Add Experience

### ISSUE THREAD

**Issue by dudihakakyan** [benhuri/Mifalot#15]
As a coach, I want to add an experience from a specific workout so that all users can keep up to date of the practice.

Test description:	
1. Adding an experience from a specific workout	
2. Access shared experiences **after** adding a new experience
3. Access shared experiences **from different users** after adding a new experience

Expected results:
1. The experience will be added to other shared experiences
2. The new experience will be found among other shared experiences
3. The user will be able to see the new experience among other shared experiences

**Comment by benhuri** [comment]
Finished
