### ISSUE TITLE
Remove Experience

### ISSUE THREAD

**Issue by dudihakakyan** [benhuri/Mifalot#16]
As a coach, I'd like to delete an experience that was not uploaded properly or found to be offensive so that it no longer appears in the app.

Test description:
1. Access to some experience and delete it	
2. Access to shared experiences from different users **after some experience was deleted**
3. Access to some experience **of another user** and try to delete it	

Expected results:
1. The experience no longer appears in the app
2. The experience no longer appears in the app
3. The deletion attempt will be rejected or the delete option will not appear

**Comment by matanankona** [comment]
Done
