### ISSUE TITLE
Comment On Experience

### ISSUE THREAD

**Issue by dudihakakyan** [benhuri/Mifalot#18]
As a coach or board member I would like to comment on experiences so that I can express my opinion about it.

Test description:
1. Enter the experience and add a comment	
2. Enter the experience **after** a new comment was added	

Expected results:
1. The comment will be successfully added to the rest of the experience responses
2. The new response will appear among the rest of the experience responses to all users

**Comment by Kfirco12** [comment]
Done, from end to end.
