### ISSUE TITLE
Presence - Update attendance list

### ISSUE THREAD

**Issue by dudihakakyan** [benhuri/Mifalot#20]
As a coach, I would like to update the attendance list so that it will saved.

Test description:
 - Pressing the save presence button	

Expected results:
- Pressing the save presence button will save the information for the pupils

**Comment by dudihakakyan** [comment]
split issue. 
second issue is here: https://github.com/benhuri/Mifalot/issues/32

**Comment by dudihakakyan** [comment]
Having trouble with access to database, issue moves from iteration0 to iteration1.

**Comment by Kfirco12** [comment]
Done.
