### ISSUE TITLE
Presence - Management members can view presences

### ISSUE THREAD

**Issue by dudihakakyan** [benhuri/Mifalot#32]
As a coach, I would like to update the attendance list so that it goes to other management members.

Test description:

* Different management members trying to view presences after the coach has pressed the save presence button.

Expected results:

* Management members will be able to view presence list.

**Comment by dudihakakyan** [comment]
Template is ready but we having trouble with access to database, issue moves from iteration1 to iteration2.

**Comment by benhuri** [comment]
We succeded connecting to the DB. Issue closed.
