### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by benhuri** [benhuri/Mifalot#9]
#### Checklist
- [x] User manual:
  - [x] The product generally
  - [x] How to Install
  - [x] How to use
  - [x] Technical support details
  - [x] Section on application of course materials
<br/>

- [x] Developer Manual:
  - [x] Code Access
  - [x] Project's License
  - [x] Code Structure
  - [x] Compilation
  - [x] Checking
  - [x] Bug list
  - [x] How to make a new version

**Comment by Kfirco12** [comment]
Documentation is  completed.
As the programming develops there is a need to update the manual and developer manuals.
